using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.TurretControls;

[GenerateTypedNameReferences]
public sealed partial class TurretControlSetting : BoxContainer
{
    public ProtoId<TurretControlSettingPrototype> ProtoId;
    public MonoToneButton IgnoreMonoToneButton;
    public MonoToneButton TargetMonoToneButton;

    public TurretControlSetting(ProtoId<TurretControlSettingPrototype> protoId, string label)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ProtoId = protoId;
        SettingLabel.Text = label;
        IgnoreMonoToneButton = IgnoreButton;
        TargetMonoToneButton = TargetButton;
    }
}
