- type: accessLevel
  id: HeadOfSecurity
  name: id-card-access-level-head-of-security

- type: accessLevel
  id: Security
  name: id-card-access-level-security

- type: accessLevel
  id: Armory
  name: id-card-access-level-armory

- type: accessLevel
  id: Brig
  name: id-card-access-level-brig

- type: accessLevel
  id: Detective
  name: id-card-access-level-detective

- type: accessGroup
  id: Security
  name: access-level-group-security
  tags:
  - HeadOfSecurity
  - Security
  - Armory
  - Brig
  - Detective
  - Cryogenics

- type: accessGroup
  id: Armory
  name: access-level-group-armory
  tags:
  - Security
  - Armory
  - Brig
