using Content.Client.UserInterface.Controls;
using Content.Shared.Dialogue;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.Dialogue;

[GenerateTypedNameReferences]
public sealed partial class DialogueBasicWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    public event Action<int>? OnResponseSelectedEvent;

    private DialogueBasicWindowBoundInterfaceState? _lastState;
    private EntityUid? _owner;

    public DialogueBasicWindow()
    {
        RobustXamlLoader.Load(this);
    }

    private void OnResponseSelected(int responseIndex)
    {
        OnResponseSelectedEvent?.Invoke(responseIndex);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateState(DialogueBasicWindowBoundInterfaceState state)
    {
        if (_owner == null || _playerManager.LocalSession?.AttachedEntity == null)
            return;

        // Do not update if the new state is the same as the last
        if (_lastState != null
            && _lastState.NodeText == state.NodeText
            && _lastState.Responses.SequenceEqual(state.Responses))
            return;

        _lastState = state;

        // Get the names of the entities involved in the dialogue
        var ownerName = Identity.Name(_owner.Value, _entityManager);
        var userName = Identity.Name(_playerManager.LocalSession.AttachedEntity.Value, _entityManager);
 
        // Update main text
        NodeText.Text = Loc.GetString(state.NodeText,
            ("OwnerName", ownerName),
            ("UserName", userName)
        );

        // Update responses
        ResponseContainer.RemoveAllChildren();

        foreach (var (responseIndex, responseText) in state.Responses)
        {
            var responseButton = new Button
            {
                Text = Loc.GetString(responseText,
                    ("OwnerName", ownerName),
                    ("UserName", userName)
                ),
                MinWidth = 200,
                MinHeight = 40,
                Margin = new Thickness(0, 0, 0, 0)
            };

            responseButton.OnPressed += args => OnResponseSelected(responseIndex);
            ResponseContainer.AddChild(responseButton);
        }
    }
}
