using Content.Client.Message;
using Content.Client.Pinpointer.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.Monitor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Content.Client.Atmos.Console;

[GenerateTypedNameReferences]
public sealed partial class AtmosMonitoringConsoleWindow : FancyWindow
{
    private readonly IEntityManager _entManager;
    private readonly SpriteSystem _spriteSystem;

    private EntityUid? _owner;
    private NetEntity? _trackedEntity;

    private AtmosMonitoringConsoleEntry[]? _airAlarms = null;
    private AtmosMonitoringConsoleEntry[]? _fireAlarms = null;
    private IEnumerable<AtmosMonitoringConsoleEntry>? _activeAlarms = null;
    private Dictionary<NetEntity, float> _deviceSilencingProgress = new();

    public event Action<NetEntity?>? SendFocusChangeMessageAction;
    public event Action<NetEntity, bool>? SendDeviceSilencedMessageAction;

    private bool _autoScrollActive = false;
    private bool _autoScrollAwaitsUpdate = false;

    private const float SilencingDuration = 2.5f;

    public AtmosMonitoringConsoleWindow(AtmosMonitoringConsoleBoundUserInterface userInterface, EntityUid? owner)
    {
        RobustXamlLoader.Load(this);
        _entManager = IoCManager.Resolve<IEntityManager>();
        _spriteSystem = _entManager.System<SpriteSystem>();

        // Pass the owner to nav map
        _owner = owner;
        NavMap.Owner = _owner;

        // Set nav map grid uid
        var stationName = Loc.GetString("atmos-monitoring-window-unknown-location");

        if (_entManager.TryGetComponent<TransformComponent>(owner, out var xform))
        {
            NavMap.MapUid = xform.GridUid;

            // Assign station name      
            if (_entManager.TryGetComponent<MetaDataComponent>(xform.GridUid, out var stationMetaData))
                stationName = stationMetaData.EntityName;

            var msg = new FormattedMessage();
            msg.AddMarkup(Loc.GetString("atmos-monitoring-window-station-name", ("stationName", stationName)));

            StationName.SetMessage(msg);
        }

        else
        {
            StationName.SetMessage(stationName);
            NavMap.Visible = false;
        }

        // Set trackable entity selected action
        NavMap.TrackedEntitySelectedAction += SetTrackedEntityFromNavMap;

        // Update nav map
        NavMap.ForceNavMapUpdate();

        // Set tab container headers
        MasterTabContainer.SetTabTitle(0, Loc.GetString("atmos-monitoring-window-tab-no-alerts"));
        MasterTabContainer.SetTabTitle(1, Loc.GetString("atmos-monitoring-window-tab-air-alarms"));
        MasterTabContainer.SetTabTitle(2, Loc.GetString("atmos-monitoring-window-tab-fire-alarms"));

        // Set UI toggles
        ShowPipeNetwork.OnToggled += _ => OnShowPipeNetworkToggled();
        ShowInactiveAlarms.OnToggled += _ => OnInactiveAlarmsToggled();

        // Set atmos monitoring message action
        SendFocusChangeMessageAction += userInterface.SendFocusChangeMessage;
        SendDeviceSilencedMessageAction += userInterface.SendDeviceSilencedMessage;
    }

    #region Toggle handling

    private void OnShowPipeNetworkToggled()
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner.Value, out var console))
            return;

        NavMap.ShowPipeNetwork = ShowPipeNetwork.Pressed;

        foreach (var device in console.AtmosDevices)
        {
            if (IsAlarm(device.Group))
                continue;

            if (ShowPipeNetwork.Pressed)
                AddTrackedEntityToNavMap(device);

            else
                NavMap.TrackedEntities.Remove(device.NetEntity);
        }
    }

    private void OnInactiveAlarmsToggled()
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner.Value, out var console))
            return;

        foreach (var device in console.AtmosDevices)
        {
            if (!IsAlarm(device.Group))
                continue;

            var alarmState = GetAlarmState(device.NetEntity, device.Group);

            if (ShowInactiveAlarms.Pressed)
                AddTrackedEntityToNavMap(device, alarmState);

            else if (alarmState <= AtmosAlarmType.Normal)
                NavMap.TrackedEntities.Remove(device.NetEntity);
        }
    }

    private void OnSilenceAlertsToggled(NetEntity netEntity, bool toggleState)
    {
        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner, out var console))
            return;

        if (toggleState)
        {
            console.SilencedDevices.Add(netEntity);
            _deviceSilencingProgress[netEntity] = SilencingDuration;
        }

        else
        {
            console.SilencedDevices.Remove(netEntity);
            _deviceSilencingProgress.Remove(netEntity);
        }

        // Update values and UI elements
        foreach (AtmosAlarmEntryContainer entryContainer in AlertsTable.Children)
        {
            if (entryContainer.NetEntity == netEntity)
                entryContainer.SilenceAlarmProgressBar.Visible = toggleState;
        }

        SendDeviceSilencedMessageAction?.Invoke(netEntity, toggleState);
    }

    #endregion

    public void UpdateUI(EntityCoordinates? consoleCoords, AtmosMonitoringConsoleEntry[] airAlarms, AtmosMonitoringConsoleEntry[] fireAlarms, AtmosFocusDeviceData? focusData)
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner.Value, out var console))
            return;

        if (_trackedEntity != focusData?.NetEntity)
        {
            SendFocusChangeMessageAction?.Invoke(_trackedEntity);
            focusData = null;
        }

        // Retain alarm data for use between updates
        _airAlarms = airAlarms;
        _fireAlarms = fireAlarms;

        var allAlarms = airAlarms.Concat(fireAlarms).ToArray();
        _activeAlarms = allAlarms.Where(x => x.AlarmState > AtmosAlarmType.Normal &&
            (!console.SilencedDevices.Contains(x.NetEntity) || _deviceSilencingProgress.ContainsKey(x.NetEntity)));

        // Reset nav map values
        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedEntities.Clear();

        // Add tracked entities to the nav map
        foreach (var device in console.AtmosDevices)
        {
            if (!NavMap.Visible)
                continue;

            AtmosAlarmType? alarmState = null;

            if (IsAlarm(device.Group))
                alarmState = GetAlarmState(device.NetEntity, device.Group);

            if (_trackedEntity != device.NetEntity)
            {
                // Skip inactive air alarms if the appropriate overlay is off
                if (!ShowInactiveAlarms.Pressed &&
                    IsAlarm(device.Group) &&
                    (alarmState == null || alarmState <= AtmosAlarmType.Normal))
                    continue;

                // Skip atmos devices if the pipe network is toggled off
                if (!ShowPipeNetwork.Pressed &&
                    !IsAlarm(device.Group))
                    continue;
            }

            AddTrackedEntityToNavMap(device, alarmState);
        }

        // Show the monitor location
        var consoleUid = _entManager.GetNetEntity(_owner);

        if (consoleCoords != null && consoleUid != null)
        {
            var texture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
            var blip = new NavMapBlip(consoleCoords.Value, texture, Color.Cyan, true, false);
            NavMap.TrackedEntities[consoleUid.Value] = blip;
        }

        // Update the nav map
        NavMap.ForceNavMapUpdate();

        // Clear excess children from the tables
        var activeAlarmCount = _activeAlarms.Count();

        while (AlertsTable.ChildCount > activeAlarmCount)
            AlertsTable.RemoveChild(AlertsTable.GetChild(AlertsTable.ChildCount - 1));

        while (AirAlarmsTable.ChildCount > airAlarms.Length)
            AirAlarmsTable.RemoveChild(AirAlarmsTable.GetChild(AirAlarmsTable.ChildCount - 1));

        while (FireAlarmsTable.ChildCount > fireAlarms.Length)
            FireAlarmsTable.RemoveChild(FireAlarmsTable.GetChild(FireAlarmsTable.ChildCount - 1));

        // Update all entries in each table
        for (int index = 0; index < _activeAlarms.Count(); index++)
        {
            var entry = _activeAlarms.ElementAt(index);
            UpdateUIEntry(entry, index, AlertsTable, console, focusData);
        }

        for (int index = 0; index < airAlarms.Count(); index++)
        {
            var entry = airAlarms.ElementAt(index);
            UpdateUIEntry(entry, index, AirAlarmsTable, console, focusData);
        }

        for (int index = 0; index < fireAlarms.Count(); index++)
        {
            var entry = fireAlarms.ElementAt(index);
            UpdateUIEntry(entry, index, FireAlarmsTable, console, focusData);
        }

        // If no alerts are active, display a message
        if (MasterTabContainer.CurrentTab == 0 && activeAlarmCount == 0)
        {
            var label = new RichTextLabel()
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            label.SetMarkup(Loc.GetString("atmos-monitoring-window-no-active-alerts", ("color", StyleNano.GoodGreenFore.ToHexNoAlpha())));

            AlertsTable.AddChild(label);
        }

        // Update the alerts tab with the number of active alerts
        if (activeAlarmCount == 0)
            MasterTabContainer.SetTabTitle(0, Loc.GetString("atmos-monitoring-window-tab-no-alerts"));

        else
            MasterTabContainer.SetTabTitle(0, Loc.GetString("atmos-monitoring-window-tab-alerts", ("value", activeAlarmCount)));

        // Auto-scroll re-enable
        if (_autoScrollAwaitsUpdate)
        {
            _autoScrollActive = true;
            _autoScrollAwaitsUpdate = false;
        }
    }

    private void AddTrackedEntityToNavMap(AtmosDeviceNavMapData metaData, AtmosAlarmType? alarmState = null)
    {
        var data = GetBlipTexture(metaData.Group, metaData.Direction);

        if (data == null)
            return;

        var texture = data.Value.Item1;
        var color = (metaData.Color != null) ? metaData.Color * data.Value.Item2 : data.Value.Item2;
        var coords = _entManager.GetCoordinates(metaData.NetCoordinates);

        if (alarmState != null)
        {
            switch (alarmState)
            {
                case AtmosAlarmType.Normal:
                    color = StyleNano.GoodGreenFore; break;
                case AtmosAlarmType.Warning:
                    color = StyleNano.ConcerningOrangeFore; break;
                case AtmosAlarmType.Danger:
                    color = StyleNano.DangerousRedFore; break;
                default:
                    color = StyleNano.DisabledFore; break;
            }

            if (_trackedEntity != null && _trackedEntity != metaData.NetEntity)
                color = color.Value * Color.DimGray;
        }

        if (color == null)
            color = Color.White;

        var selectable = IsAlarm(metaData.Group);
        var blip = new NavMapBlip(coords, _spriteSystem.Frame0(texture), color.Value, _trackedEntity == metaData.NetEntity, selectable);

        if (!IsAlarm(metaData.Group))
        {
            blip.ScalingCoefficient = 0.015f;
            blip.ScalingType = NavMapBlipScaling.Linear;
        }

        NavMap.TrackedEntities[metaData.NetEntity] = blip;
    }

    private void UpdateUIEntry(AtmosMonitoringConsoleEntry entry, int index, Control table, AtmosMonitoringConsoleComponent console, AtmosFocusDeviceData? focusData = null)
    {
        // Make new UI entry if required
        if (index >= table.ChildCount)
        {
            var newEntryContainer = new AtmosAlarmEntryContainer(entry.NetEntity, _entManager.GetCoordinates(entry.Coordinates));

            // On click
            newEntryContainer.FocusButton.OnButtonUp += args =>
            {
                var prevTrackedEntity = _trackedEntity;

                if (_trackedEntity == entry.NetEntity)
                {
                    _trackedEntity = null;
                }

                else
                {
                    _trackedEntity = newEntryContainer.NetEntity;
                    NavMap.CenterToCoordinates(_entManager.GetCoordinates(entry.Coordinates));
                }

                // Send message to console that the focus has changed
                SendFocusChangeMessageAction?.Invoke(_trackedEntity);

                // Update affected UI elements across all tables
                UpdateConsoleTable(console, AlertsTable, _trackedEntity, prevTrackedEntity);
                UpdateConsoleTable(console, AirAlarmsTable, _trackedEntity, prevTrackedEntity);
                UpdateConsoleTable(console, FireAlarmsTable, _trackedEntity, prevTrackedEntity);
            };

            // On toggling the silence check box
            newEntryContainer.SilenceCheckBox.OnToggled += _ => OnSilenceAlertsToggled(entry.NetEntity, newEntryContainer.SilenceCheckBox.Pressed);

            // Add the entry to the current table
            table.AddChild(newEntryContainer);
        }

        // Update values and UI elements
        var tableChild = table.GetChild(index);

        if (tableChild is not AtmosAlarmEntryContainer)
        {
            table.RemoveChild(tableChild);
            UpdateUIEntry(entry, index, table, console, focusData);

            return;
        }

        var entryContainer = tableChild as AtmosAlarmEntryContainer;

        if (entryContainer == null)
            return;

        entryContainer.UpdateEntry(entry, entry.NetEntity == _trackedEntity, focusData);
        entryContainer.SilenceCheckBox.Pressed = console.SilencedDevices.Contains(entry.NetEntity);
        entryContainer.SilenceAlarmProgressBar.Visible = (table == AlertsTable && _deviceSilencingProgress.ContainsKey(entry.NetEntity));
    }

    private void UpdateConsoleTable(AtmosMonitoringConsoleComponent console, Control table, NetEntity? currTrackedEntity, NetEntity? prevTrackedEntity)
    {
        foreach (var child in table.Children)
        {
            if (child is not AtmosAlarmEntryContainer)
                continue;

            var castAlert = (AtmosAlarmEntryContainer) child;

            if (castAlert.NetEntity == prevTrackedEntity)
                castAlert.RemoveAsFocus();

            else if (castAlert.NetEntity == currTrackedEntity)
                castAlert.SetAsFocus();

            if (castAlert?.Coordinates == null)
                continue;

            var device = console.AtmosDevices.FirstOrNull(x => x.NetEntity == castAlert.NetEntity);

            if (device == null)
                continue;

            var alarmState = GetAlarmState(device.Value.NetEntity, device.Value.Group);

            if (currTrackedEntity != device.Value.NetEntity &&
                !ShowInactiveAlarms.Pressed &&
                alarmState <= AtmosAlarmType.Normal)
                continue;

            AddTrackedEntityToNavMap(device.Value, alarmState);
        }
    }

    private void SetTrackedEntityFromNavMap(NetEntity? netEntity)
    {
        if (netEntity == null)
            return;

        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner, out var console))
            return;

        _trackedEntity = netEntity;

        if (netEntity != null)
        {
            // Tab switching
            if (MasterTabContainer.CurrentTab != 0 || _activeAlarms?.Any(x => x.NetEntity == netEntity) == false)
            {
                var device = console.AtmosDevices.FirstOrNull(x => x.NetEntity == netEntity);

                switch (device?.Group)
                {
                    case AtmosMonitoringConsoleGroup.AirAlarm:
                        MasterTabContainer.CurrentTab = 1; break;
                    case AtmosMonitoringConsoleGroup.FireAlarm:
                        MasterTabContainer.CurrentTab = 2; break;
                }
            }

            // Get the scroll position of the selected entity on the selected button the UI
            ActivateAutoScrollToFocus();
        }

        // Send message to console that the focus has changed
        SendFocusChangeMessageAction?.Invoke(_trackedEntity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        AutoScrollToFocus();

        // Device silencing update
        foreach ((var device, var remainingTime) in _deviceSilencingProgress)
        {
            var t = remainingTime - args.DeltaSeconds;

            if (t <= 0)
                _deviceSilencingProgress.Remove(device);

            else
                _deviceSilencingProgress[device] = t;
        }
    }

    private void ActivateAutoScrollToFocus()
    {
        _autoScrollActive = false;
        _autoScrollAwaitsUpdate = true;
    }

    private void AutoScrollToFocus()
    {
        if (!_autoScrollActive)
            return;

        var scroll = MasterTabContainer.Children.ElementAt(MasterTabContainer.CurrentTab) as ScrollContainer;
        if (scroll == null)
            return;

        if (!TryGetVerticalScrollbar(scroll, out var vScrollbar))
            return;

        if (!TryGetNextScrollPosition(out float? nextScrollPosition))
            return;

        vScrollbar.ValueTarget = nextScrollPosition.Value;

        if (MathHelper.CloseToPercent(vScrollbar.Value, vScrollbar.ValueTarget))
            _autoScrollActive = false;
    }

    private bool TryGetVerticalScrollbar(ScrollContainer scroll, [NotNullWhen(true)] out VScrollBar? vScrollBar)
    {
        vScrollBar = null;

        foreach (var child in scroll.Children)
        {
            if (child is not VScrollBar)
                continue;

            var castChild = child as VScrollBar;

            if (castChild != null)
            {
                vScrollBar = castChild;
                return true;
            }
        }

        return false;
    }

    private bool TryGetNextScrollPosition([NotNullWhen(true)] out float? nextScrollPosition)
    {
        nextScrollPosition = null;

        var scroll = MasterTabContainer.Children.ElementAt(MasterTabContainer.CurrentTab) as ScrollContainer;
        if (scroll == null)
            return false;

        var container = scroll.Children.ElementAt(0) as BoxContainer;
        if (container == null || container.Children.Count() == 0)
            return false;

        // Exit if the heights of the children haven't been initialized yet
        if (!container.Children.Any(x => x.Height > 0))
            return false;

        nextScrollPosition = 0;

        foreach (var control in container.Children)
        {
            if (control == null || control is not AtmosAlarmEntryContainer)
                continue;

            if (((AtmosAlarmEntryContainer) control).NetEntity == _trackedEntity)
                return true;

            nextScrollPosition += control.Height;
        }

        // Failed to find control
        nextScrollPosition = null;

        return false;
    }

    private bool IsAlarm(AtmosMonitoringConsoleGroup group)
    {
        return group == AtmosMonitoringConsoleGroup.AirAlarm || group == AtmosMonitoringConsoleGroup.FireAlarm;
    }

    private AtmosAlarmType GetAlarmState(NetEntity netEntity, AtmosMonitoringConsoleGroup group)
    {
        var alarms = (group == AtmosMonitoringConsoleGroup.AirAlarm) ? _airAlarms : _fireAlarms;
        var alarmState = alarms?.FirstOrNull(x => x.NetEntity == netEntity)?.AlarmState;

        if (alarmState == null)
            return AtmosAlarmType.Invalid;

        return alarmState.Value;
    }

    private (SpriteSpecifier.Texture, Color)? GetBlipTexture(AtmosMonitoringConsoleGroup group, Direction? direction = null)
    {
        (SpriteSpecifier.Texture, Color)? output = null;

        switch (group)
        {
            case AtmosMonitoringConsoleGroup.GasPump:
                switch (direction)
                {
                    case Direction.North:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/pump_north.png")), Color.DarkGray); break;
                    case Direction.South:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/pump_south.png")), Color.DarkGray); break;
                    case Direction.East:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/pump_east.png")), Color.DarkGray); break;
                    case Direction.West:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/pump_west.png")), Color.DarkGray); break;
                }; break;
            case AtmosMonitoringConsoleGroup.GasValve:
                switch (direction)
                {
                    case Direction.North:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/valve_north_south.png")), Color.DarkGray); break;
                    case Direction.South:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/valve_north_south.png")), Color.DarkGray); break;
                    case Direction.East:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/valve_east_west.png")), Color.DarkGray); break;
                    case Direction.West:
                        output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/valve_east_west.png")), Color.DarkGray); break;
                }; break;
            case AtmosMonitoringConsoleGroup.GasOutlet:
                output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/gas_vent.png")), Color.DarkGray); break;
            case AtmosMonitoringConsoleGroup.GasInlet:
                output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/AtmosMonitoring/gas_scrubber.png")), Color.DarkGray); break;
            case AtmosMonitoringConsoleGroup.AirAlarm:
                output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_star.png")), Color.White); break;
            case AtmosMonitoringConsoleGroup.FireAlarm:
                output = (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_star.png")), Color.White); break;
        }

        return output;
    }
}
