using Content.Client.Stylesheets;
using Content.Shared.Access;
using Content.Shared.TurretController;
using Content.Shared.Turrets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Numerics;

namespace Content.Client.TurretController;

[GenerateTypedNameReferences]
public sealed partial class TurretControllerWindow : BaseWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;
    private readonly IResourceCache _cache;

    private EntityUid? _owner;
    private DeployableTurretControllerUiKey? _uiKey;

    private int _tabIndex = 0;

    // Events
    private event Action<int>? OnAccessGroupChangedEvent;
    public event Action<AccessLevelPrototype, bool>? OnAccessLevelChangedEvent;
    public event Action<int>? OnArmamentSettingChangedEvent;

    // Colors
    private Color[] _themeColors = [Color.FromHex("#33e633"), Color.FromHex("#dfb827"), Color.FromHex("#da2a2a")];

    public TurretControllerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _cache = IoCManager.Resolve<IResourceCache>();

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        OnAccessGroupChangedEvent += OnAccessGroupChanged;

        var smallFont = _cache.NotoStack(size: 8);
        Footer.FontOverride = smallFont;
    }

    private void Initialize()
    {
        if (_owner == null || _uiKey == null)
            return;

        SafeButton.OnButtonUp += args => OnArmamentButtonPressed(SafeButton, -1);
        StunButton.OnButtonUp += args => OnArmamentButtonPressed(StunButton, 0);
        LethalButton.OnButtonUp += args => OnArmamentButtonPressed(LethalButton, 1);

        if (!_entManager.TryGetComponent<DeployableTurretControllerComponent>(_owner, out var turretController))
            return;

        UpdateTheme(turretController.ArmamentState);

        RefreshAccessControls();
    }

    private void OnArmamentButtonPressed(Button pressedButton, int index)
    {
        UpdateTheme(index);
        pressedButton.Pressed = false;

        OnArmamentSettingChangedEvent?.Invoke(index);
    }

    private void UpdateTheme(int index)
    {
        SafeButton.Pressed = index == -1;
        StunButton.Pressed = index == 0;
        LethalButton.Pressed = index == 1;

        var shiftedIndex = index + 1;

        if (shiftedIndex >= 0 && shiftedIndex < _themeColors.Length)
            ContentsContainer.Modulate = _themeColors[shiftedIndex];
    }

    public void SetOwnerAndUiKey(EntityUid owner, DeployableTurretControllerUiKey uiKey)
    {
        _owner = owner;
        _uiKey = uiKey;

        Initialize();
    }

    public void UpdateState(DeployableTurretControllerWindowBoundInterfaceState state)
    {
        UpdateTheme(state.ArmamentState);
        RefreshLinkedTurrets(state.TurretStates);
        RefreshAccessControls();
    }

    public void RefreshLinkedTurrets(List<(string, string)> turretStates)
    {
        var turretCount = turretStates.Count;
        var hasTurrets = turretCount > 0;

        NoLinkedTurretsText.Visible = !hasTurrets;
        LinkedTurretsContainer.Visible = hasTurrets;

        if (!hasTurrets)
            return;

        LinkedTurretsContainer.RemoveAllChildren();

        foreach (var turretState in turretStates)
        {
            var box = new BoxContainer()
            {
                HorizontalExpand = true,
            };

            var label = new Label()
            {
                Text = Loc.GetString("turret-controls-window-turret-status", ("device", turretState.Item1), ("status", Loc.GetString(turretState.Item2))),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(10f, 0f, 10f, 0f),
                HorizontalExpand = true,
                SetHeight = 20f,
            };

            label.AddStyleClass("ConsoleText");

            box.AddChild(label);
            LinkedTurretsContainer.AddChild(box);
        }
    }

    public void RefreshAccessControls()
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<DeployableTurretControllerComponent>(_owner, out var turretControls))
            return;

        if (!_entManager.TryGetComponent<TurretTargetSettingsComponent>(_owner, out var turretTargeting))
            return;

        var groupedAccessLevels = new Dictionary<AccessGroupPrototype, HashSet<AccessLevelPrototype>>();
 
        AccessGroupList.DisposeAllChildren();
        AccessLevelGrid.DisposeAllChildren();

        foreach (var accessGroup in turretControls.AccessGroups)
        {
            if (!_protoManager.TryIndex(accessGroup, out var accessGroupProto))
                continue;

            groupedAccessLevels.Add(accessGroupProto, new());
        }

        if (_protoManager.TryIndex<AccessGroupPrototype>("General", out var generalAccessProto) &&
            groupedAccessLevels.Keys.FirstOrDefault(x => x.ID != "General") == null)
        {
            groupedAccessLevels.Add(generalAccessProto, new());
        }

        // Try to combine the access levels under broader access groups
        foreach (var accessLevel in turretControls.AccessLevels)
        {
            if (!_protoManager.TryIndex(accessLevel, out var accessLevelProto))
                continue;

            IEnumerable<AccessGroupPrototype> associatedGroups = groupedAccessLevels.Keys.Where(x => x.Tags.Contains(accessLevelProto.ID) == true);

            if (!associatedGroups.Any() && generalAccessProto != null)
                groupedAccessLevels[generalAccessProto].Add(accessLevelProto);

            else
            {
                foreach (var group in associatedGroups)
                    groupedAccessLevels[group].Add(accessLevelProto);
            }
        }

        // Remove access groups with no entries
        foreach (var (group, accessLevels) in groupedAccessLevels)
        {
            if (accessLevels.Count == 0)
                groupedAccessLevels.Remove(group);
        }

        if (_tabIndex >= groupedAccessLevels.Count)
            _tabIndex = groupedAccessLevels.Count - 1;

        // Generate buttons for the access groups
        var orderedAccessGroups = groupedAccessLevels.Keys.OrderBy(x => x.GetAccessGroupName()).ToList();

        for (int i = 0; i < orderedAccessGroups.Count; i++)
        {
            var accessGroup = orderedAccessGroups[i];

            var newButton = new MonoToneButton
            {
                Text = accessGroup.Name != null ? Loc.GetString(accessGroup.Name) : "???",
                ToggleMode = true,
                Pressed = _tabIndex == orderedAccessGroups.IndexOf(accessGroup),
            };

            AccessGroupList.AddChild(newButton);

            newButton.OnPressed += _ =>
            {
                OnAccessGroupChangedEvent?.Invoke(newButton.GetPositionInParent());
            };

            // Style the button depending where it is on the list
            if (orderedAccessGroups.Count > 1)
            {
                if (i == 0)
                    newButton.AddStyleClass("OpenLeft");

                else if (orderedAccessGroups.Count > 1 && i == (orderedAccessGroups.Count - 1))
                    newButton.AddStyleClass("OpenRight");

                else
                    newButton.AddStyleClass("OpenBoth");
            }
        }

        // Generate buttons for the current tab
        var accessLevelsForTab = groupedAccessLevels[orderedAccessGroups[_tabIndex]];
        accessLevelsForTab = accessLevelsForTab.OrderBy(x => x.GetAccessLevelName()).ToHashSet();

        foreach (var accessLevel in accessLevelsForTab)
        {
            var newButton = new MonoToneCheckBox
            {
                Text = accessLevel.GetAccessLevelName(),
                ToggleMode = true,
                Margin = new Thickness(0f, 2f),
                Pressed = turretTargeting.ExemptAccessLevels.Contains(accessLevel),
            };

            AccessLevelGrid.AddChild(newButton);
 
            newButton.OnPressed += args =>
            {
                OnAccessLevelChangedEvent?.Invoke(accessLevel, newButton.Pressed);
            };
        }
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    private void OnAccessGroupChanged(int newTabIndex)
    {
        var oldAccessGroupButton = AccessGroupList.GetChild(_tabIndex) as Button;

        if (oldAccessGroupButton == null)
            return;

        oldAccessGroupButton.Pressed = (newTabIndex == _tabIndex);

        if (newTabIndex == _tabIndex)
            return;

        _tabIndex = newTabIndex;
        RefreshAccessControls();
    }
}

public sealed class MonoToneButton : Button
{
    public float BorderThickness = 2f;
    public Color ForegroundColor = Color.White;
    public Color BackgroundColor = new Color(55, 55, 55);

    private PanelContainer _innerPanel;

    public MonoToneButton()
    {
        Label.AddStyleClass("ConsoleText");

        ModulateSelfOverride = ForegroundColor;

        _innerPanel = new PanelContainer()
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        AddChild(_innerPanel);
        _innerPanel.SetPositionFirst();
    }

    protected override void StylePropertiesChanged()
    {
        base.StylePropertiesChanged();

        if (!this.TryGetStyleProperty<StyleBoxTexture>(StylePropertyStyleBox, out var box))
            return;

        Label.ModulateSelfOverride = this.Pressed ? BackgroundColor : ForegroundColor;

        _innerPanel.PanelOverride = new StyleBoxTexture(box)
        {
            Modulate = this.Pressed ? ForegroundColor : BackgroundColor,
        };

        _innerPanel.Margin = new Thickness
            (BorderThickness - box.GetContentMargin(StyleBox.Margin.Left),
            BorderThickness - box.GetContentMargin(StyleBox.Margin.Top),
            BorderThickness - box.GetContentMargin(StyleBox.Margin.Right),
            BorderThickness - box.GetContentMargin(StyleBox.Margin.Bottom));
    }
}

public sealed class MonoToneCheckBox : CheckBox
{
    public MonoToneCheckBox()
    {
        Label.AddStyleClass("ConsoleText");

        TextureRect.RemoveStyleClass(StyleClassCheckBox);
        TextureRect.AddStyleClass(StyleNano.StyleClassCheckBoxWhite);
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        if (TextureRect != null)
        {
            if (Pressed)
                TextureRect.AddStyleClass(StyleNano.StyleClassCheckBoxWhiteChecked);
            else
                TextureRect.RemoveStyleClass(StyleNano.StyleClassCheckBoxWhiteChecked);
        }
    }
}
