- type: turretControlSetting
  id: TargetCyborgs
  name: turret-control-setting-target-cyborgs
  
- type: turretControlSetting
  id: TargetBasicSilicons
  name: turret-control-setting-target-basic-silicons
  
- type: turretControlSetting
  id: TargetAnimalsAndXenos
  name: turret-control-setting-target-animals-and-xenos
  
- type: turretControlSetting
  id: TargetIsHoldingContraband
  name: turret-control-setting-target-is-holding-contraband
  
- type: turretControlSetting
  id: TargetWantedCriminals
  name: turret-control-setting-target-wanted-criminals
  
- type: turretControlSetting
  id: TargetUnauthorizedCrew
  name: turret-control-setting-target-unauthorized-crew
